// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5cu-qWdhPzbodPYv6hDMm0eH9b0EB7YA',
    appId: '1:46191395254:web:46f9f8e631311f23658117',
    messagingSenderId: '46191395254',
    projectId: 'medlink-744a7',
    authDomain: 'medlink-744a7.firebaseapp.com',
    storageBucket: 'medlink-744a7.firebasestorage.app',
    measurementId: 'G-73713ZJLBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIC5Q5OEchLax53kh_jbdF3itoSFcIpts',
    appId: '1:46191395254:android:cdf8d903dcd48eaa658117',
    messagingSenderId: '46191395254',
    projectId: 'medlink-744a7',
    storageBucket: 'medlink-744a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWjEA64iFCZ9NN5RXKN-ddi_H9_7vxOlo',
    appId: '1:46191395254:ios:70111aeeba8e5b20658117',
    messagingSenderId: '46191395254',
    projectId: 'medlink-744a7',
    storageBucket: 'medlink-744a7.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWjEA64iFCZ9NN5RXKN-ddi_H9_7vxOlo',
    appId: '1:46191395254:ios:70111aeeba8e5b20658117',
    messagingSenderId: '46191395254',
    projectId: 'medlink-744a7',
    storageBucket: 'medlink-744a7.firebasestorage.app',
    iosBundleId: 'com.example.medlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5cu-qWdhPzbodPYv6hDMm0eH9b0EB7YA',
    appId: '1:46191395254:web:c51cdb9307e2a520658117',
    messagingSenderId: '46191395254',
    projectId: 'medlink-744a7',
    authDomain: 'medlink-744a7.firebaseapp.com',
    storageBucket: 'medlink-744a7.firebasestorage.app',
    measurementId: 'G-BME06KYXF7',
  );
}
